name: CI/CD Pipeline


on:
  push:
    paths-ignore:
      - '**.md' 
    branches:
      - master
  release:
    types: [created]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.namesecret }}  
          SONAR_TOKEN: ${{ secrets.sonartoken }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=monitoramento_analisedeprojeto
            -Dsonar.organization=monitoramento

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04
    needs: sonarcloud
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.namesecret }}
          password: ${{ secrets.senhasecret }}

      - name: Display Dockerfile
        run: |
          if [ -f Dockerfile ]; then
            cat Dockerfile
          else
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Build Docker Image with BuildKit
        run: |
          export DOCKER_BUILDKIT=1
          docker build -t julianobcgato/projetoapi:${{ github.run_number }} .

      - name: Push Docker Image
        run: docker push julianobcgato/projetoapi:${{ github.run_number }}

  alterar_tag:
    name: Update Deployment YAML
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository for GitOps
        uses: actions/checkout@v3
        with:
          repository: julianobcgato/projetoargocd
          token: ${{ secrets.argocdtoken }}

      - name: Set run number
        run: echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Display deployment.yaml
        run: |
          if [ -f ./gitops/deployment.yaml ]; then
            cat ./gitops/deployment.yaml
          else
            echo "deployment.yaml not found!"
            exit 1
          fi

      - name: Modify yaml File
        run: |
          sed -i "s/^        image: .*/        image: julianobcgato\/projetoapi:$RUN_NUMBER/" ./gitops/deployment.yaml

      - name: Commit and Push Changes
        run: |
          git config user.name "Juliano"
          git config user.email "julianobcgato@gmail.com"
          git add ./gitops/deployment.yaml
          git commit -m "Update image tag in deployment.yaml"
          git push

  deploy:
  name: Deploy to Kubernetes
  runs-on: ubuntu-latest
  needs: alterar_tag
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.5.4

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.26.0'

    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy with Helm
      run: |
        helm upgrade --install prometheus ./helm/prometheus --namespace monitoring --create-namespace
        helm upgrade --install grafana ./helm/grafana --namespace monitoring --create-namespace
